# Generated by Django 5.2.8 on 2026-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_quantity_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='destination',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
