# Generated by Django 5.2.8 on 2026-09-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orderplaced_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='received_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='received_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
