# Generated by Django 5.2.8 on 2026-09-20 08:47

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[myapp.models.validate_phone_number]),
        ),
    ]
